[profileMode]
  enabled = true
  title = "흰돌건설(주)"
  subtitle = ""
  imageUrl = "hndol_logo_with_title.png"
  imageWidth = 200
  imageHeight = 100

ShowShareButtons = false
ShowReadingTime = false
ShowCodeCopyButtons = false
defaultTheme = "light"
disableThemeToggle = true

[label]
  text = "흰돌건설(주)"
  icon = "hndol_logo.png"
  iconHeight = 35